<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <DisableImplicitRevitUsings>true</DisableImplicitRevitUsings>
    <ImplicitUsings>true</ImplicitUsings>
    <Configurations>Debug R20;Debug R21;Debug R22;Debug R23;Debug R24;Debug R25</Configurations>
    <Configurations>$(Configurations);Release R20;Release R21;Release R22;Release R23;Release R24;Release R25</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration.Contains('R20'))">
    <RevitVersion>2020</RevitVersion>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('R21'))">
    <RevitVersion>2021</RevitVersion>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('R22'))">
    <RevitVersion>2022</RevitVersion>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('R23'))">
    <RevitVersion>2023</RevitVersion>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('R24'))">
    <RevitVersion>2024</RevitVersion>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('R25'))">
    <RevitVersion>2025</RevitVersion>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Remove="Views\Converters\**" />
    <EmbeddedResource Remove="Views\Converters\**" />
    <None Remove="Views\Converters\**" />
    <Page Remove="Views\Converters\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Nice3point.Revit.Build.Tasks" Version="2.*" />
    <PackageReference Include="Nice3point.Revit.Toolkit" Version="$(RevitVersion).*" />
    <PackageReference Include="Nice3point.Revit.Extensions" Version="$(RevitVersion).*" />
    <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="$(RevitVersion).*" />
    <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="$(RevitVersion).*" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.*" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Autodesk.Revit.DB" />
    <Using Include="JetBrains.Annotations" />
    <Using Include="Nice3point.Revit.Toolkit" />
    <Using Include="Nice3point.Revit.Extensions" />
    <Using Include="CommunityToolkit.Mvvm.ComponentModel" />
    <Using Include="CommunityToolkit.Mvvm.Input" />
  </ItemGroup>

  <PropertyGroup>
    <PackageAssemblyVersion></PackageAssemblyVersion>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('Debug'))">
    <IncludePackageReferencesDuringMarkupCompilation>false</IncludePackageReferencesDuringMarkupCompilation>
    <Revision Condition="'$(Revision)' == ''">$([MSBuild]::Divide($([System.DateTime]::Now.TimeOfDay.TotalSeconds), 4).ToString('F0'))</Revision>
    <PackageAssemblyVersion>.Dev.$(Revision)</PackageAssemblyVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>$(MSBuildProjectName)</PackageId>
    <AssemblyName>$(PackageId)$(PackageAssemblyVersion)</AssemblyName>
  </PropertyGroup>

</Project>